---
title: "April 9th: Draft of Chilodonella Culture Maintenance Protocol"
author: "Lucy K Brennan"
date: "2026-04-09"
categories: [Chilodonella Culture Maintenance, "Living" Protocol, Observation]
description: "Progress in beginning different protocols and interesting Chilodonella observations for today"

---

# Overview

Today, I moved my Chilodonella into a new well in my six-welled-plate. I then began to draft a procedure which I have been using to maintain my Chilodonella culture for the past few months. It is significantly less complex than the reading I have done into maintaining a Heliophrya culture, but the overall procedure is likely widely applicable to similar ciliates. 

# Goals

- Continue working on finalizing my Chilodonella Maintenance Protocol 
- Begin a draft for a similar Heliophrya maintenance procedure 
- Draft a Tetrahymena culture maintenance protocol, because it will be of use to other lab members

# Methods

## Setup

Before moving over my culture, I used the microscope to check on my cells. 

## Procedures

My Draft Maintenance Protocol: 
1. Obtain a 6 well tray
2. Using heat treated trim dell water, fill the first well (in the top left corner) 3/4 of the way full 
3. Using the tweezers, add a single rice grain from the green lidded container to your well
4. With a 20-200 microliter micro pipette, add 100-200 micro liters from an established culture sample
5. Store crim dell water and 6 well tray in sample fridge
6. To maintain a clean culture, repeat the process moving into a new well of your 6 well tray every 5-7 days

## Observations

I thought it was super interesting that instead of being spread out around the well like they normally are, they were all clustered in one corner. Despite this unusual observations here were still cells in different stages of development. 

# Analysis

I counted between 15-20 cells in view at 4x lens magnification for 30 seconds. While this is typical the day I move my culture, this was not consistent throughout the plate like it normally is. 

# Discussion

I will come into the lab early next week to make sure the cells in my new well are beginning to reproduce and I will make note of their density throughout the well. 

# Next Steps

- [ ] Check on Chilodonella on Monday 
- [ ] Share my protocol with other members of the lab, so they can test it and provide feedback for each step
- [ ] Start Tetrahymena culture procedure 


---
